export const START_FETCHING_ANNOUNCEMENT = 'features/Announcement/START_FETCHING_ANNOUNCEMENT'
export const ERROR_FETCHING_ANNOUNCEMENT = 'features/Announcement/ERROR_FETCHING_ANNOUNCEMENT'
export const SUCCESS_FETCHING_ANNOUNCEMENT = 'features/Announcement/SUCCESS_FETCHING_ANNOUNCEMENT'