export const START_FETCHING_COMPANY= 'features/Company/START_FETCHING_COMPANY'
export const ERROR_FETCHING_COMPANY= 'features/Company/ERROR_FETCHING_COMPANY'
export const SUCCESS_FETCHING_COMPANY= 'features/Company/SUCCESS_FETCHING_COMPANY'